/**
 * Comprehensive Disease Information Database
 *
 * Contains detailed information for all 50+ diseases supported by the PRS Calculator.
 * Data includes heritability estimates from peer-reviewed research, key genetic variants,
 * risk factors, and evidence-based prevention strategies.
 *
 * Sources:
 * - PGS Catalog (https://www.pgscatalog.org/)
 * - UK Biobank genetic studies
 * - Published genome-wide association studies (GWAS)
 * - Twin studies and heritability meta-analyses
 */

export const DISEASE_CATEGORIES = {
  cardiovascular: {
    name: 'Cardiovascular',
    description: 'Conditions affecting the heart and blood vessels',
    icon: 'Heart',
    color: '#dc2626',
  },
  oncology: {
    name: 'Oncology',
    description: 'Cancer and malignant neoplasms',
    icon: 'Shield',
    color: '#7c3aed',
  },
  metabolic: {
    name: 'Metabolic',
    description: 'Metabolic disorders and endocrine conditions',
    icon: 'Activity',
    color: '#2563eb',
  },
  neurological: {
    name: 'Neurological',
    description: 'Conditions affecting the brain and nervous system',
    icon: 'Brain',
    color: '#0891b2',
  },
  psychiatric: {
    name: 'Psychiatric',
    description: 'Mental health and behavioral conditions',
    icon: 'Mind',
    color: '#6366f1',
  },
  autoimmune: {
    name: 'Autoimmune',
    description: 'Immune system disorders',
    icon: 'Shield',
    color: '#059669',
  },
  respiratory: {
    name: 'Respiratory',
    description: 'Lung and airway conditions',
    icon: 'Wind',
    color: '#0ea5e9',
  },
  ophthalmologic: {
    name: 'Ophthalmologic',
    description: 'Eye and vision conditions',
    icon: 'Eye',
    color: '#8b5cf6',
  },
  musculoskeletal: {
    name: 'Musculoskeletal',
    description: 'Bone and joint conditions',
    icon: 'Bone',
    color: '#ea580c',
  },
  dermatologic: {
    name: 'Dermatologic',
    description: 'Skin conditions',
    icon: 'Layers',
    color: '#ec4899',
  },
  renal: {
    name: 'Renal',
    description: 'Kidney conditions',
    icon: 'Droplet',
    color: '#14b8a6',
  },
  endocrine: {
    name: 'Endocrine',
    description: 'Thyroid and hormonal conditions',
    icon: 'Zap',
    color: '#f59e0b',
  },
};

export const DISEASES = {
  // =====================
  // CARDIOVASCULAR (8)
  // =====================
  cad: {
    id: 'cad',
    name: 'Coronary Artery Disease',
    pgsId: 'PGS000018',
    category: 'cardiovascular',
    heritability: '40-60%',
    heritabilitySource: 'Zdravkovic et al., 2002; Kathiresan & Srivastava, 2012',
    description: 'Coronary artery disease (CAD) occurs when the major blood vessels supplying the heart become damaged or diseased, typically due to plaque buildup (atherosclerosis). It is the leading cause of death worldwide and a major cause of heart attacks.',
    keyGenes: ['LDLR', 'APOB', 'PCSK9', '9p21.3 locus', 'LPA', 'SORT1'],
    riskFactors: [
      'High LDL cholesterol',
      'High blood pressure',
      'Smoking',
      'Diabetes',
      'Obesity',
      'Family history',
      'Sedentary lifestyle',
      'Chronic stress',
    ],
    prevention: [
      'Maintain healthy cholesterol levels through diet and medication if needed',
      'Regular aerobic exercise (150+ minutes/week)',
      'Heart-healthy diet (Mediterranean, DASH)',
      'Smoking cessation',
      'Blood pressure management',
      'Maintain healthy weight',
      'Limit alcohol consumption',
      'Regular cardiovascular screening after age 40',
    ],
    prevalence: 'Affects approximately 18 million adults in the US',
  },
  afib: {
    id: 'afib',
    name: 'Atrial Fibrillation',
    pgsId: 'PGS000016',
    category: 'cardiovascular',
    heritability: '60-70%',
    heritabilitySource: 'Lubitz et al., 2010; Christophersen et al., 2017',
    description: 'Atrial fibrillation (AFib) is an irregular and often rapid heart rhythm that can lead to blood clots in the heart. It increases risk of stroke, heart failure, and other heart-related complications.',
    keyGenes: ['PITX2', 'KCNN3', 'ZFHX3', 'CAV1', 'PRRX1', 'SCN5A'],
    riskFactors: [
      'Advanced age',
      'High blood pressure',
      'Heart disease',
      'Obesity',
      'Sleep apnea',
      'Excessive alcohol',
      'Hyperthyroidism',
      'Family history',
    ],
    prevention: [
      'Blood pressure control',
      'Weight management',
      'Limit alcohol and caffeine',
      'Treat sleep apnea',
      'Regular physical activity',
      'Manage underlying heart conditions',
      'Avoid stimulants',
    ],
    prevalence: 'Affects 2.7-6.1 million people in the US',
  },
  stroke: {
    id: 'stroke',
    name: 'Stroke',
    pgsId: 'PGS000039',
    category: 'cardiovascular',
    heritability: '30-40%',
    heritabilitySource: 'Bevan et al., 2012; Dichgans et al., 2019',
    description: 'Stroke occurs when blood supply to part of the brain is interrupted or reduced, preventing brain tissue from getting oxygen and nutrients. It is a leading cause of death and disability worldwide.',
    keyGenes: ['PITX2', 'ZFHX3', 'HDAC9', '9p21.3 locus', 'ABO', 'TSPAN2'],
    riskFactors: [
      'High blood pressure',
      'Atrial fibrillation',
      'Diabetes',
      'High cholesterol',
      'Smoking',
      'Obesity',
      'Physical inactivity',
      'Heavy alcohol use',
    ],
    prevention: [
      'Blood pressure management (most important)',
      'Anticoagulation for AFib if indicated',
      'Smoking cessation',
      'Diabetes control',
      'Cholesterol management',
      'Regular physical activity',
      'Healthy diet (low sodium)',
      'Moderate alcohol consumption',
    ],
    prevalence: 'Nearly 800,000 strokes occur annually in the US',
  },
  hypertension: {
    id: 'hypertension',
    name: 'Hypertension',
    pgsId: 'PGS000012',
    category: 'cardiovascular',
    heritability: '30-50%',
    heritabilitySource: 'Levy et al., 2009; Ehret & Caulfield, 2013',
    description: 'Hypertension (high blood pressure) is a chronic condition where blood pressure in the arteries is persistently elevated. It is a major risk factor for heart disease, stroke, and kidney disease.',
    keyGenes: ['AGT', 'ACE', 'ADD1', 'NOS3', 'NPPA', 'CYP17A1', 'FGF5'],
    riskFactors: [
      'Excess sodium intake',
      'Low potassium intake',
      'Obesity',
      'Physical inactivity',
      'Excess alcohol',
      'Chronic stress',
      'Age',
      'Family history',
    ],
    prevention: [
      'DASH diet (low sodium, high potassium)',
      'Regular aerobic exercise',
      'Weight management',
      'Limit alcohol',
      'Smoking cessation',
      'Stress management',
      'Regular blood pressure monitoring',
      'Adequate sleep',
    ],
    prevalence: 'Affects nearly half of US adults (47%)',
  },
  heart_failure: {
    id: 'heart_failure',
    name: 'Heart Failure',
    pgsId: 'PGS000115',
    category: 'cardiovascular',
    heritability: '26-34%',
    heritabilitySource: 'Lee et al., 2016; Shah et al., 2020',
    description: 'Heart failure is a chronic condition where the heart cannot pump blood efficiently enough to meet the body\'s needs. It often develops after other conditions have damaged or weakened the heart.',
    keyGenes: ['TTN', 'LMNA', 'MYH7', 'MYBPC3', 'BAG3', 'SCN5A'],
    riskFactors: [
      'Coronary artery disease',
      'Hypertension',
      'Previous heart attack',
      'Diabetes',
      'Obesity',
      'Valvular heart disease',
      'Cardiomyopathy',
      'Excessive alcohol',
    ],
    prevention: [
      'Control blood pressure',
      'Manage diabetes',
      'Maintain healthy weight',
      'Regular exercise',
      'Limit salt intake',
      'Avoid excessive alcohol',
      'Treat underlying heart conditions',
      'Regular cardiac screening if at risk',
    ],
    prevalence: 'Affects approximately 6.2 million adults in the US',
  },
  venous_thromboembolism: {
    id: 'venous_thromboembolism',
    name: 'Venous Thromboembolism',
    pgsId: 'PGS000043',
    category: 'cardiovascular',
    heritability: '50-60%',
    heritabilitySource: 'Souto et al., 2000; Heit et al., 2016',
    description: 'Venous thromboembolism (VTE) includes deep vein thrombosis (blood clots in deep veins) and pulmonary embolism (blood clots in lungs). It is a serious but preventable condition.',
    keyGenes: ['F5 (Factor V Leiden)', 'F2 (Prothrombin)', 'ABO', 'FGG', 'PROC', 'PROS1'],
    riskFactors: [
      'Prolonged immobility',
      'Surgery',
      'Cancer',
      'Pregnancy',
      'Oral contraceptives/HRT',
      'Obesity',
      'Inherited clotting disorders',
      'Previous VTE',
    ],
    prevention: [
      'Stay active during long trips',
      'Early mobilization after surgery',
      'Compression stockings when indicated',
      'Maintain healthy weight',
      'Stay hydrated',
      'Avoid prolonged sitting',
      'Prophylactic anticoagulation when indicated',
    ],
    prevalence: 'Affects 1-2 per 1,000 people annually',
  },
  aortic_aneurysm: {
    id: 'aortic_aneurysm',
    name: 'Aortic Aneurysm',
    pgsId: 'PGS000081',
    category: 'cardiovascular',
    heritability: '70-80%',
    heritabilitySource: 'Clifton et al., 1977; Larsson et al., 2009',
    description: 'An aortic aneurysm is a bulge in the wall of the aorta, the main blood vessel carrying blood from the heart. If it ruptures, it can cause life-threatening internal bleeding.',
    keyGenes: ['FBN1', 'TGFBR1', 'TGFBR2', 'SMAD3', 'MYH11', 'ACTA2'],
    riskFactors: [
      'Smoking (strongest modifiable risk)',
      'High blood pressure',
      'Atherosclerosis',
      'Male sex',
      'Age over 65',
      'Family history',
      'Connective tissue disorders',
    ],
    prevention: [
      'Smoking cessation (most important)',
      'Blood pressure control',
      'Cholesterol management',
      'Regular screening if family history',
      'Avoid heavy lifting with known aneurysm',
      'Ultrasound screening for at-risk individuals',
    ],
    prevalence: 'Affects 1-2% of people over 65',
  },
  peripheral_artery_disease: {
    id: 'peripheral_artery_disease',
    name: 'Peripheral Artery Disease',
    pgsId: 'PGS000117',
    category: 'cardiovascular',
    heritability: '20-30%',
    heritabilitySource: 'Valentine et al., 2004; Kullo et al., 2006',
    description: 'Peripheral artery disease (PAD) is a circulatory condition in which narrowed blood vessels reduce blood flow to the limbs, especially the legs, causing pain during walking.',
    keyGenes: ['CHRNA3', '9p21.3 locus', 'LPA', 'ABO', 'LDLR'],
    riskFactors: [
      'Smoking (strongest risk factor)',
      'Diabetes',
      'High blood pressure',
      'High cholesterol',
      'Age over 50',
      'Obesity',
      'Family history of PAD/CVD',
    ],
    prevention: [
      'Smoking cessation',
      'Diabetes management',
      'Blood pressure control',
      'Cholesterol management',
      'Regular exercise (walking programs)',
      'Healthy diet',
      'Foot care for diabetics',
    ],
    prevalence: 'Affects 8-12 million Americans',
  },

  // =====================
  // ONCOLOGY (12)
  // =====================
  breast_cancer: {
    id: 'breast_cancer',
    name: 'Breast Cancer',
    pgsId: 'PGS000004',
    category: 'oncology',
    heritability: '25-30%',
    heritabilitySource: 'Lichtenstein et al., 2000; Mucci et al., 2016',
    description: 'Breast cancer is a disease where cells in the breast grow out of control. It is the most common cancer in women worldwide and can also occur in men. Early detection significantly improves outcomes.',
    keyGenes: ['BRCA1', 'BRCA2', 'PALB2', 'CHEK2', 'ATM', 'TP53', 'FGFR2', 'TOX3'],
    riskFactors: [
      'Family history (especially BRCA mutations)',
      'Increasing age',
      'Early menstruation/late menopause',
      'No pregnancies or late first pregnancy',
      'Hormone replacement therapy',
      'Obesity (postmenopausal)',
      'Alcohol consumption',
      'Dense breast tissue',
    ],
    prevention: [
      'Regular mammography screening',
      'Breast self-examination awareness',
      'Maintain healthy weight',
      'Limit alcohol consumption',
      'Regular physical activity',
      'Consider genetic testing if family history',
      'Discuss HRT risks with doctor',
      'Breastfeeding if possible',
    ],
    prevalence: '1 in 8 women will develop breast cancer',
  },
  prostate_cancer: {
    id: 'prostate_cancer',
    name: 'Prostate Cancer',
    pgsId: 'PGS000662',
    category: 'oncology',
    heritability: '57-58%',
    heritabilitySource: 'Hjelmborg et al., 2014; Mucci et al., 2016',
    description: 'Prostate cancer is cancer that occurs in the prostate gland. It is one of the most common cancers in men, but many prostate cancers grow slowly and may not cause serious harm.',
    keyGenes: ['HOXB13', '8q24 region', 'MSMB', 'KLK3', 'BRCA2', 'ATM'],
    riskFactors: [
      'Age over 50',
      'African ancestry',
      'Family history',
      'Obesity',
      'Diet high in red meat/dairy',
      'BRCA1/2 mutations',
    ],
    prevention: [
      'Discuss PSA screening with doctor',
      'Maintain healthy weight',
      'Exercise regularly',
      'Eat diet rich in fruits and vegetables',
      'Limit red meat and high-fat dairy',
      'Consider genetic testing if family history',
    ],
    prevalence: '1 in 8 men will be diagnosed with prostate cancer',
  },
  colorectal_cancer: {
    id: 'colorectal_cancer',
    name: 'Colorectal Cancer',
    pgsId: 'PGS000055',
    category: 'oncology',
    heritability: '12-35%',
    heritabilitySource: 'Lichtenstein et al., 2000; Czene et al., 2002',
    description: 'Colorectal cancer begins in the colon or rectum. Most cases develop slowly from precancerous polyps, making screening highly effective for prevention and early detection.',
    keyGenes: ['APC', 'MLH1', 'MSH2', 'MSH6', 'PMS2', 'SMAD7', 'TCF7L2'],
    riskFactors: [
      'Age over 50',
      'Inflammatory bowel disease',
      'Family history/Lynch syndrome',
      'Diet high in processed meat',
      'Obesity',
      'Sedentary lifestyle',
      'Smoking',
      'Heavy alcohol use',
    ],
    prevention: [
      'Regular colonoscopy screening (starting age 45)',
      'Remove precancerous polyps',
      'High-fiber diet',
      'Limit red and processed meat',
      'Maintain healthy weight',
      'Regular physical activity',
      'Limit alcohol',
      'Avoid smoking',
    ],
    prevalence: '3rd most common cancer in both men and women',
  },
  lung_cancer: {
    id: 'lung_cancer',
    name: 'Lung Cancer',
    pgsId: 'PGS000070',
    category: 'oncology',
    heritability: '8-18%',
    heritabilitySource: 'Lichtenstein et al., 2000; Dai et al., 2019',
    description: 'Lung cancer is the leading cause of cancer death worldwide. While smoking is the primary cause, genetic factors influence susceptibility, especially among smokers.',
    keyGenes: ['CHRNA5', 'CHRNA3', 'TERT', 'TP63', 'EGFR', 'BRCA2'],
    riskFactors: [
      'Smoking (causes ~85% of cases)',
      'Secondhand smoke',
      'Radon exposure',
      'Asbestos exposure',
      'Air pollution',
      'Family history',
      'Previous radiation therapy',
    ],
    prevention: [
      'Never smoke or quit smoking',
      'Avoid secondhand smoke',
      'Test home for radon',
      'Avoid workplace carcinogens',
      'Low-dose CT screening for high-risk individuals',
      'Eat diet rich in fruits and vegetables',
    ],
    prevalence: 'Leading cause of cancer death in the US',
  },
  pancreatic_cancer: {
    id: 'pancreatic_cancer',
    name: 'Pancreatic Cancer',
    pgsId: 'PGS000058',
    category: 'oncology',
    heritability: '5-10%',
    heritabilitySource: 'Klein et al., 2018; Amundadottir et al., 2009',
    description: 'Pancreatic cancer begins in the tissues of the pancreas. It is often detected late and has a low survival rate, making prevention and early detection crucial.',
    keyGenes: ['BRCA2', 'PALB2', 'CDKN2A', 'ATM', 'STK11', 'ABO'],
    riskFactors: [
      'Smoking',
      'Chronic pancreatitis',
      'Long-standing diabetes',
      'Obesity',
      'Family history',
      'Certain genetic syndromes',
      'Heavy alcohol use',
    ],
    prevention: [
      'Avoid tobacco',
      'Maintain healthy weight',
      'Limit alcohol',
      'Manage diabetes',
      'Surveillance for high-risk individuals',
      'Genetic counseling if family history',
    ],
    prevalence: 'Affects about 60,000 Americans annually',
  },
  ovarian_cancer: {
    id: 'ovarian_cancer',
    name: 'Ovarian Cancer',
    pgsId: 'PGS000054',
    category: 'oncology',
    heritability: '20-25%',
    heritabilitySource: 'Lichtenstein et al., 2000; Jervis et al., 2014',
    description: 'Ovarian cancer often goes undetected until it has spread within the pelvis and abdomen. Women with BRCA mutations have significantly elevated risk.',
    keyGenes: ['BRCA1', 'BRCA2', 'RAD51C', 'RAD51D', 'BRIP1', 'PALB2'],
    riskFactors: [
      'BRCA1/2 mutations',
      'Family history',
      'Older age',
      'Endometriosis',
      'Never having been pregnant',
      'Obesity',
      'Hormone replacement therapy',
    ],
    prevention: [
      'Genetic testing and counseling',
      'Oral contraceptives (reduce risk)',
      'Risk-reducing surgery for high-risk women',
      'Awareness of symptoms',
      'Regular gynecologic exams',
      'Maintain healthy weight',
    ],
    prevalence: 'About 1 in 78 women will develop ovarian cancer',
  },
  melanoma: {
    id: 'melanoma',
    name: 'Melanoma',
    pgsId: 'PGS000066',
    category: 'oncology',
    heritability: '55-58%',
    heritabilitySource: 'Mucci et al., 2016; Law et al., 2012',
    description: 'Melanoma is the most serious type of skin cancer, developing in the cells that give skin its color. Early detection is critical for successful treatment.',
    keyGenes: ['CDKN2A', 'MC1R', 'IRF4', 'TYR', 'OCA2', 'SLC45A2'],
    riskFactors: [
      'UV radiation exposure',
      'Fair skin, light hair, blue eyes',
      'Multiple moles',
      'Family history',
      'History of sunburns',
      'Weakened immune system',
      'Living near equator/high altitude',
    ],
    prevention: [
      'Use broad-spectrum SPF 30+ sunscreen',
      'Avoid peak sun hours (10am-4pm)',
      'Wear protective clothing',
      'Avoid tanning beds',
      'Regular skin self-examination',
      'Annual dermatologist visits',
      'Know the ABCDEs of melanoma',
    ],
    prevalence: 'Incidence has risen dramatically in recent decades',
  },
  bladder_cancer: {
    id: 'bladder_cancer',
    name: 'Bladder Cancer',
    pgsId: 'PGS000068',
    category: 'oncology',
    heritability: '30-40%',
    heritabilitySource: 'Aben et al., 2002; Garcia-Closas et al., 2005',
    description: 'Bladder cancer most often begins in the cells lining the inside of the bladder. It is more common in men and often caught early due to visible symptoms like blood in urine.',
    keyGenes: ['NAT2', 'GSTM1', 'TP63', 'MYC', 'PSCA', 'FGFR3'],
    riskFactors: [
      'Smoking (strongest risk factor)',
      'Occupational chemical exposure',
      'Chronic bladder infections',
      'Previous cancer treatment',
      'Arsenic exposure',
      'Male sex',
      'Older age',
    ],
    prevention: [
      'Quit smoking',
      'Limit exposure to industrial chemicals',
      'Drink plenty of fluids',
      'Eat diet rich in fruits and vegetables',
      'Prompt treatment of bladder infections',
    ],
    prevalence: '4th most common cancer in men',
  },
  kidney_cancer: {
    id: 'kidney_cancer',
    name: 'Kidney Cancer',
    pgsId: 'PGS000074',
    category: 'oncology',
    heritability: '38-42%',
    heritabilitySource: 'Mucci et al., 2016; Scelo et al., 2017',
    description: 'Kidney cancer originates in the kidneys. The most common type in adults is renal cell carcinoma. Early kidney cancer often has no symptoms.',
    keyGenes: ['VHL', 'MET', 'EPAS1', 'BAP1', 'PBRM1'],
    riskFactors: [
      'Smoking',
      'Obesity',
      'High blood pressure',
      'Family history',
      'Workplace chemical exposure',
      'Advanced kidney disease',
      'Certain genetic syndromes',
    ],
    prevention: [
      'Quit smoking',
      'Maintain healthy weight',
      'Control blood pressure',
      'Avoid workplace toxins',
      'Regular medical checkups',
    ],
    prevalence: 'About 76,000 new cases annually in the US',
  },
  thyroid_cancer: {
    id: 'thyroid_cancer',
    name: 'Thyroid Cancer',
    pgsId: 'PGS000082',
    category: 'oncology',
    heritability: '53%',
    heritabilitySource: 'Czene et al., 2002; Goldgar et al., 1994',
    description: 'Thyroid cancer occurs in the cells of the thyroid gland. Most types are highly treatable and have excellent survival rates when detected early.',
    keyGenes: ['FOXE1', 'NKX2-1', 'DIRC3', 'MBIP', 'RET'],
    riskFactors: [
      'Radiation exposure (especially childhood)',
      'Family history',
      'Female sex',
      'Certain genetic syndromes (MEN2)',
      'Iodine deficiency',
      'Obesity',
    ],
    prevention: [
      'Limit unnecessary radiation exposure',
      'Genetic testing if family history',
      'Regular thyroid examination',
      'Maintain healthy weight',
    ],
    prevalence: 'Incidence has tripled in recent decades',
  },
  endometrial_cancer: {
    id: 'endometrial_cancer',
    name: 'Endometrial Cancer',
    pgsId: 'PGS000061',
    category: 'oncology',
    heritability: '27%',
    heritabilitySource: 'Lu et al., 2007; Mucci et al., 2016',
    description: 'Endometrial cancer begins in the lining of the uterus (endometrium). It is the most common gynecologic cancer and often detected early due to abnormal bleeding.',
    keyGenes: ['MLH1', 'MSH2', 'MSH6', 'PMS2', 'HNF1B', 'CYP19A1'],
    riskFactors: [
      'Obesity (strongest risk factor)',
      'Estrogen-only HRT',
      'Never having been pregnant',
      'Early menstruation/late menopause',
      'Polycystic ovary syndrome',
      'Lynch syndrome',
      'Tamoxifen use',
      'Type 2 diabetes',
    ],
    prevention: [
      'Maintain healthy weight',
      'Physical activity',
      'Combined HRT if needed (not estrogen only)',
      'Oral contraceptives (reduce risk)',
      'Lynch syndrome screening',
      'Report abnormal bleeding promptly',
    ],
    prevalence: 'Most common uterine cancer',
  },
  testicular_cancer: {
    id: 'testicular_cancer',
    name: 'Testicular Cancer',
    pgsId: 'PGS000078',
    category: 'oncology',
    heritability: '37-49%',
    heritabilitySource: 'Czene et al., 2002; Litchfield et al., 2017',
    description: 'Testicular cancer occurs in the testicles. It is the most common cancer in young men ages 15-35 but is highly treatable even when spread to other areas.',
    keyGenes: ['KITLG', 'SPRY4', 'BAK1', 'DMRT1', 'TERT', 'ATF7IP'],
    riskFactors: [
      'Undescended testicle',
      'Family history',
      'Personal history in other testicle',
      'White race',
      'HIV infection',
      'Infertility',
    ],
    prevention: [
      'Regular testicular self-examination',
      'Surgical correction of undescended testicle',
      'Awareness of symptoms',
      'Prompt evaluation of testicular changes',
    ],
    prevalence: 'About 9,000 new cases annually in the US',
  },

  // =====================
  // METABOLIC (6)
  // =====================
  t2d: {
    id: 't2d',
    name: 'Type 2 Diabetes',
    pgsId: 'PGS000014',
    category: 'metabolic',
    heritability: '40-70%',
    heritabilitySource: 'Poulsen et al., 1999; Almgren et al., 2011',
    description: 'Type 2 diabetes is a chronic condition affecting how the body metabolizes glucose. It is characterized by insulin resistance and relative insulin deficiency.',
    keyGenes: ['TCF7L2', 'PPARG', 'KCNJ11', 'SLC30A8', 'CDKAL1', 'CDKN2A/B', 'FTO'],
    riskFactors: [
      'Overweight/obesity',
      'Physical inactivity',
      'Family history',
      'Age over 45',
      'Prediabetes',
      'Gestational diabetes history',
      'Polycystic ovary syndrome',
      'Certain ethnicities',
    ],
    prevention: [
      'Weight loss (5-7% if overweight)',
      '150 minutes/week moderate exercise',
      'Healthy diet (low refined carbs)',
      'Avoid sugary beverages',
      'Regular blood glucose screening',
      'Metformin for high-risk individuals',
      'Sleep 7-9 hours nightly',
    ],
    prevalence: 'Affects 37 million Americans (11% of population)',
  },
  t1d: {
    id: 't1d',
    name: 'Type 1 Diabetes',
    pgsId: 'PGS000021',
    category: 'metabolic',
    heritability: '80-90%',
    heritabilitySource: 'Redondo et al., 2008; Noble & Erlich, 2012',
    description: 'Type 1 diabetes is an autoimmune condition where the immune system destroys insulin-producing cells in the pancreas. It usually appears in childhood or young adulthood.',
    keyGenes: ['HLA-DRB1', 'HLA-DQB1', 'INS', 'PTPN22', 'CTLA4', 'IL2RA'],
    riskFactors: [
      'Family history',
      'Genetics (HLA genes)',
      'Certain viral infections',
      'Geography (more common farther from equator)',
      'Age (peaks in childhood)',
    ],
    prevention: [
      'No proven prevention currently',
      'Research ongoing on immune therapies',
      'Antibody screening for at-risk families',
      'Teplizumab (FDA approved to delay onset)',
      'Clinical trials available',
    ],
    prevalence: 'Affects 1.6 million Americans',
  },
  obesity: {
    id: 'obesity',
    name: 'Obesity (BMI)',
    pgsId: 'PGS000027',
    category: 'metabolic',
    heritability: '40-70%',
    heritabilitySource: 'Maes et al., 1997; Elks et al., 2012',
    description: 'Obesity is a complex condition involving excessive body fat that increases risk for many health problems. Both genetic and environmental factors contribute.',
    keyGenes: ['FTO', 'MC4R', 'TMEM18', 'BDNF', 'GNPDA2', 'SEC16B'],
    riskFactors: [
      'Calorie-dense diet',
      'Sedentary lifestyle',
      'Genetics',
      'Certain medications',
      'Sleep deprivation',
      'Stress and emotional factors',
      'Gut microbiome',
      'Socioeconomic factors',
    ],
    prevention: [
      'Regular physical activity',
      'Balanced diet with whole foods',
      'Portion control',
      'Limit processed foods and sugary drinks',
      'Adequate sleep (7-9 hours)',
      'Stress management',
      'Regular weight monitoring',
      'Behavioral support if needed',
    ],
    prevalence: 'Affects 42% of US adults',
  },
  gout: {
    id: 'gout',
    name: 'Gout',
    pgsId: 'PGS000048',
    category: 'metabolic',
    heritability: '60-70%',
    heritabilitySource: 'Kuo et al., 2015; Major et al., 2018',
    description: 'Gout is a form of inflammatory arthritis caused by elevated uric acid levels leading to crystal deposits in joints. It causes sudden, severe attacks of pain and swelling.',
    keyGenes: ['SLC2A9', 'ABCG2', 'SLC22A12', 'SLC17A1', 'GCKR'],
    riskFactors: [
      'High purine diet (red meat, seafood)',
      'Alcohol (especially beer)',
      'Obesity',
      'Certain medications (diuretics)',
      'Kidney disease',
      'Male sex',
      'Sugary beverages',
    ],
    prevention: [
      'Limit high-purine foods',
      'Avoid or limit alcohol',
      'Stay well hydrated',
      'Maintain healthy weight',
      'Limit sugary drinks',
      'Dairy may be protective',
      'Medication for recurrent gout',
    ],
    prevalence: 'Affects about 9 million Americans',
  },
  nafld: {
    id: 'nafld',
    name: 'Non-Alcoholic Fatty Liver Disease',
    pgsId: 'PGS000113',
    category: 'metabolic',
    heritability: '20-50%',
    heritabilitySource: 'Schwimmer et al., 2009; Romeo et al., 2020',
    description: 'NAFLD is accumulation of fat in the liver in people who drink little or no alcohol. It ranges from simple fatty liver to more serious NASH that can progress to cirrhosis.',
    keyGenes: ['PNPLA3', 'TM6SF2', 'MBOAT7', 'GCKR', 'HSD17B13'],
    riskFactors: [
      'Obesity',
      'Type 2 diabetes',
      'Metabolic syndrome',
      'High triglycerides',
      'Rapid weight loss',
      'Certain medications',
      'Sleep apnea',
    ],
    prevention: [
      'Achieve and maintain healthy weight',
      'Regular exercise',
      'Mediterranean diet',
      'Avoid excessive fructose',
      'Limit alcohol',
      'Control blood sugar and lipids',
      'Coffee may be protective',
    ],
    prevalence: 'Affects 25% of adults worldwide',
  },
  hyperlipidemia: {
    id: 'hyperlipidemia',
    name: 'Hyperlipidemia',
    pgsId: 'PGS000688',
    category: 'metabolic',
    heritability: '40-60%',
    heritabilitySource: 'Willer et al., 2013; Teslovich et al., 2010',
    description: 'Hyperlipidemia refers to elevated levels of lipids (fats) in the blood, including cholesterol and triglycerides. It is a major risk factor for cardiovascular disease.',
    keyGenes: ['LDLR', 'APOB', 'PCSK9', 'APOE', 'CETP', 'LPL', 'LIPC'],
    riskFactors: [
      'Diet high in saturated fat',
      'Obesity',
      'Lack of physical activity',
      'Type 2 diabetes',
      'Hypothyroidism',
      'Familial hypercholesterolemia',
      'Certain medications',
    ],
    prevention: [
      'Heart-healthy diet',
      'Regular aerobic exercise',
      'Maintain healthy weight',
      'Avoid trans fats',
      'Limit saturated fats',
      'Statins or other medications when indicated',
      'Regular lipid panel screening',
    ],
    prevalence: 'Affects over 93 million US adults',
  },

  // =====================
  // NEUROLOGICAL (6)
  // =====================
  alzheimers: {
    id: 'alzheimers',
    name: "Alzheimer's Disease",
    pgsId: 'PGS000334',
    category: 'neurological',
    heritability: '60-80%',
    heritabilitySource: 'Gatz et al., 2006; Ridge et al., 2016',
    description: "Alzheimer's disease is a progressive neurological disorder causing brain cells to degenerate and die, leading to memory loss and cognitive decline. It is the most common cause of dementia.",
    keyGenes: ['APOE (e4 allele)', 'APP', 'PSEN1', 'PSEN2', 'TREM2', 'CLU', 'BIN1'],
    riskFactors: [
      'Age (strongest risk factor)',
      'APOE e4 allele',
      'Family history',
      'Down syndrome',
      'Head trauma',
      'Cardiovascular disease risk factors',
      'Lower education level',
    ],
    prevention: [
      'Regular physical exercise',
      'Cognitive stimulation and lifelong learning',
      'Social engagement',
      'Mediterranean/MIND diet',
      'Adequate sleep',
      'Cardiovascular health management',
      'Hearing loss treatment',
      'Limit alcohol',
    ],
    prevalence: 'Affects 6.7 million Americans over 65',
  },
  parkinsons: {
    id: 'parkinsons',
    name: "Parkinson's Disease",
    pgsId: 'PGS000089',
    category: 'neurological',
    heritability: '25-40%',
    heritabilitySource: 'Wirdefeldt et al., 2011; Keller et al., 2012',
    description: "Parkinson's disease is a progressive nervous system disorder affecting movement. It develops gradually, often starting with tremors and stiffness.",
    keyGenes: ['SNCA', 'LRRK2', 'GBA', 'PARK7', 'PINK1', 'PRKN', 'VPS35'],
    riskFactors: [
      'Age over 60',
      'Male sex',
      'Family history',
      'Pesticide exposure',
      'Head trauma',
      'Certain genetic mutations',
      'Rural living',
    ],
    prevention: [
      'Regular aerobic exercise',
      'Caffeine consumption (may be protective)',
      'Avoid pesticide exposure',
      'Mediterranean diet',
      'Protect against head injury',
    ],
    prevalence: 'Affects nearly 1 million Americans',
  },
  migraine: {
    id: 'migraine',
    name: 'Migraine',
    pgsId: 'PGS000040',
    category: 'neurological',
    heritability: '40-60%',
    heritabilitySource: 'Mulder et al., 2003; Gormley et al., 2016',
    description: 'Migraine is a neurological condition causing intense, debilitating headaches often accompanied by nausea, vomiting, and sensitivity to light and sound.',
    keyGenes: ['TRPM8', 'LRP1', 'PRDM16', 'MTDH', 'MEF2D', 'CACNA1A'],
    riskFactors: [
      'Family history',
      'Female sex (3x more common)',
      'Hormonal changes',
      'Stress',
      'Sleep disturbances',
      'Certain foods and additives',
      'Weather changes',
      'Sensory stimuli',
    ],
    prevention: [
      'Identify and avoid triggers',
      'Regular sleep schedule',
      'Stress management',
      'Regular meals',
      'Stay hydrated',
      'Regular exercise',
      'Preventive medications for frequent migraines',
      'Limit caffeine',
    ],
    prevalence: 'Affects 12% of Americans',
  },
  epilepsy: {
    id: 'epilepsy',
    name: 'Epilepsy',
    pgsId: 'PGS000086',
    category: 'neurological',
    heritability: '25-70%',
    heritabilitySource: 'Berkovic et al., 1998; Speed et al., 2014',
    description: 'Epilepsy is a neurological disorder marked by recurrent, unprovoked seizures. It can be caused by various factors and affects people of all ages.',
    keyGenes: ['SCN1A', 'SCN2A', 'KCNQ2', 'GABRA1', 'DEPDC5', 'SLC2A1'],
    riskFactors: [
      'Head trauma',
      'Brain conditions (stroke, tumor)',
      'Infections (meningitis, encephalitis)',
      'Prenatal brain development issues',
      'Family history',
      'Certain genetic syndromes',
      'Febrile seizures in childhood',
    ],
    prevention: [
      'Prevent head injuries (helmets, seat belts)',
      'Good prenatal care',
      'Cardiovascular health',
      'Hand hygiene (prevent infections)',
      'Vaccination',
      'Take medications as prescribed',
    ],
    prevalence: 'Affects 3.4 million Americans',
  },
  als: {
    id: 'als',
    name: 'Amyotrophic Lateral Sclerosis',
    pgsId: 'PGS000093',
    category: 'neurological',
    heritability: '40-60%',
    heritabilitySource: 'Al-Chalabi et al., 2010; van Rheenen et al., 2016',
    description: 'ALS (Lou Gehrig\'s disease) is a progressive neurodegenerative disease affecting nerve cells in the brain and spinal cord, leading to loss of muscle control.',
    keyGenes: ['SOD1', 'C9orf72', 'TARDBP', 'FUS', 'NEK1', 'KIF5A'],
    riskFactors: [
      'Age 40-70',
      'Male sex (slightly higher risk)',
      'Family history',
      'Military service',
      'Smoking',
      'Lead exposure',
    ],
    prevention: [
      'No proven prevention',
      'Smoking avoidance',
      'Genetic counseling if family history',
      'Research participation',
    ],
    prevalence: 'Affects about 31,000 Americans',
  },
  restless_legs: {
    id: 'restless_legs',
    name: 'Restless Legs Syndrome',
    pgsId: 'PGS000088',
    category: 'neurological',
    heritability: '50-60%',
    heritabilitySource: 'Winkelmann et al., 2007; Schormair et al., 2017',
    description: 'Restless legs syndrome (RLS) causes an uncontrollable urge to move the legs, usually due to uncomfortable sensations, typically worse at rest and in the evening.',
    keyGenes: ['BTBD9', 'MEIS1', 'MAP2K5', 'PTPRD', 'TOX3'],
    riskFactors: [
      'Family history',
      'Iron deficiency',
      'Pregnancy',
      'Kidney failure',
      'Peripheral neuropathy',
      'Certain medications',
      'Parkinson\'s disease',
    ],
    prevention: [
      'Check and treat iron deficiency',
      'Regular exercise (not close to bedtime)',
      'Good sleep hygiene',
      'Reduce caffeine and alcohol',
      'Leg stretches before bed',
      'Avoid medications that worsen RLS',
    ],
    prevalence: 'Affects 7-10% of US population',
  },

  // =====================
  // PSYCHIATRIC (7)
  // =====================
  depression: {
    id: 'depression',
    name: 'Major Depression',
    pgsId: 'PGS000297',
    category: 'psychiatric',
    heritability: '37-40%',
    heritabilitySource: 'Sullivan et al., 2000; Wray et al., 2018',
    description: 'Major depressive disorder is a mood disorder causing persistent feelings of sadness and loss of interest. It affects how you feel, think, and behave.',
    keyGenes: ['SLC6A4', 'BDNF', 'DRD2', 'FKBP5', 'NRXN1', 'CACNA1C'],
    riskFactors: [
      'Family history',
      'Trauma or stress',
      'Chronic illness',
      'Certain medications',
      'Substance abuse',
      'Hormonal changes',
      'Social isolation',
      'Early life adversity',
    ],
    prevention: [
      'Regular physical exercise',
      'Strong social connections',
      'Stress management techniques',
      'Adequate sleep',
      'Limit alcohol',
      'Seek help early',
      'Cognitive behavioral therapy',
      'Mindfulness practices',
    ],
    prevalence: 'Affects 21 million US adults (8.4%)',
  },
  bipolar_disorder: {
    id: 'bipolar_disorder',
    name: 'Bipolar Disorder',
    pgsId: 'PGS000049',
    category: 'psychiatric',
    heritability: '60-85%',
    heritabilitySource: 'Smoller & Finn, 2003; Stahl et al., 2019',
    description: 'Bipolar disorder causes extreme mood swings including emotional highs (mania or hypomania) and lows (depression). Episodes can affect sleep, energy, behavior, and judgment.',
    keyGenes: ['CACNA1C', 'ANK3', 'ODZ4', 'NCAN', 'SYNE1', 'TRANK1'],
    riskFactors: [
      'Family history (strongest predictor)',
      'High-stress periods',
      'Traumatic events',
      'Drug or alcohol abuse',
      'Major life changes',
    ],
    prevention: [
      'Early recognition and treatment',
      'Medication adherence',
      'Regular sleep schedule',
      'Avoid alcohol and drugs',
      'Stress management',
      'Mood tracking',
      'Strong support system',
    ],
    prevalence: 'Affects 2.8% of US adults',
  },
  schizophrenia: {
    id: 'schizophrenia',
    name: 'Schizophrenia',
    pgsId: 'PGS000052',
    category: 'psychiatric',
    heritability: '79-81%',
    heritabilitySource: 'Sullivan et al., 2003; Hilker et al., 2018',
    description: 'Schizophrenia is a serious mental disorder affecting how a person thinks, feels, and behaves. People may seem like they have lost touch with reality.',
    keyGenes: ['DRD2', 'ZNF804A', 'NRGN', 'TCF4', 'MIR137', 'C4A'],
    riskFactors: [
      'Family history',
      'Pregnancy/birth complications',
      'Childhood adversity',
      'Urban environment',
      'Cannabis use in adolescence',
      'Social isolation',
      'Migration',
    ],
    prevention: [
      'Avoid cannabis, especially in teens',
      'Early intervention for at-risk youth',
      'Prenatal care',
      'Reduce childhood trauma',
      'Social support',
      'Early treatment of symptoms',
    ],
    prevalence: 'Affects about 1% of population',
  },
  adhd: {
    id: 'adhd',
    name: 'ADHD',
    pgsId: 'PGS000091',
    category: 'psychiatric',
    heritability: '70-80%',
    heritabilitySource: 'Faraone & Larsson, 2019; Demontis et al., 2019',
    description: 'Attention-deficit/hyperactivity disorder (ADHD) is a neurodevelopmental disorder characterized by inattention, hyperactivity, and impulsivity that interferes with functioning.',
    keyGenes: ['DRD4', 'DRD5', 'SLC6A3', 'SNAP25', 'FOXP2', 'DUSP6'],
    riskFactors: [
      'Family history',
      'Premature birth',
      'Low birth weight',
      'Lead exposure',
      'Maternal smoking during pregnancy',
      'Brain injury',
    ],
    prevention: [
      'Avoid smoking during pregnancy',
      'Avoid alcohol during pregnancy',
      'Reduce lead exposure',
      'Early intervention services',
      'Structured environment',
      'Regular physical activity',
    ],
    prevalence: 'Affects 4.4% of US adults',
  },
  anxiety: {
    id: 'anxiety',
    name: 'Anxiety Disorder',
    pgsId: 'PGS000099',
    category: 'psychiatric',
    heritability: '30-40%',
    heritabilitySource: 'Hettema et al., 2001; Purves et al., 2020',
    description: 'Anxiety disorders involve excessive fear or worry that interferes with daily activities. They include generalized anxiety, panic disorder, social anxiety, and specific phobias.',
    keyGenes: ['CRHR1', 'COMT', 'NPSR1', 'GABRA2', 'SLC6A4'],
    riskFactors: [
      'Family history',
      'Trauma',
      'Stress buildup',
      'Personality factors',
      'Other mental health disorders',
      'Medical conditions',
      'Substance use',
    ],
    prevention: [
      'Regular exercise',
      'Stress management',
      'Limit caffeine and alcohol',
      'Adequate sleep',
      'Social support',
      'Cognitive behavioral techniques',
      'Mindfulness and relaxation',
      'Early treatment',
    ],
    prevalence: 'Affects 19% of US adults annually',
  },
  ptsd: {
    id: 'ptsd',
    name: 'PTSD',
    pgsId: 'PGS000100',
    category: 'psychiatric',
    heritability: '30-40%',
    heritabilitySource: 'Stein et al., 2002; Nievergelt et al., 2019',
    description: 'Post-traumatic stress disorder (PTSD) develops after exposure to a terrifying event. Symptoms include flashbacks, nightmares, severe anxiety, and uncontrollable thoughts about the event.',
    keyGenes: ['FKBP5', 'CRHR1', 'ADCYAP1R1', 'OPRL1', 'SLC6A4'],
    riskFactors: [
      'Experiencing trauma',
      'Previous mental health issues',
      'Lack of support',
      'Additional stress after trauma',
      'Family history of mental illness',
      'Childhood adversity',
    ],
    prevention: [
      'Early intervention after trauma',
      'Strong social support',
      'Professional counseling',
      'Trauma-informed care',
      'Resilience building',
      'Avoid self-medication with substances',
    ],
    prevalence: 'Affects 3.6% of US adults annually',
  },
  insomnia: {
    id: 'insomnia',
    name: 'Insomnia',
    pgsId: 'PGS000108',
    category: 'psychiatric',
    heritability: '40-60%',
    heritabilitySource: 'Watson et al., 2006; Jansen et al., 2019',
    description: 'Insomnia is a sleep disorder making it hard to fall asleep, stay asleep, or get quality sleep, despite having adequate time for sleep.',
    keyGenes: ['MEIS1', 'PER2', 'CLOCK', 'BTBD9', 'PAX8'],
    riskFactors: [
      'Stress',
      'Irregular sleep schedule',
      'Mental health disorders',
      'Medications',
      'Caffeine and stimulants',
      'Medical conditions',
      'Age',
      'Shift work',
    ],
    prevention: [
      'Consistent sleep schedule',
      'Comfortable sleep environment',
      'Limit screen time before bed',
      'Avoid caffeine after noon',
      'Regular exercise (not late evening)',
      'Relaxation techniques',
      'Cognitive behavioral therapy for insomnia',
    ],
    prevalence: 'Affects 10-30% of adults',
  },

  // =====================
  // AUTOIMMUNE (7)
  // =====================
  rheumatoid_arthritis: {
    id: 'rheumatoid_arthritis',
    name: 'Rheumatoid Arthritis',
    pgsId: 'PGS000024',
    category: 'autoimmune',
    heritability: '50-60%',
    heritabilitySource: 'MacGregor et al., 2000; Okada et al., 2014',
    description: 'Rheumatoid arthritis is a chronic inflammatory disorder affecting the joints, causing painful swelling that can eventually result in bone erosion and joint deformity.',
    keyGenes: ['HLA-DRB1 (shared epitope)', 'PTPN22', 'STAT4', 'TRAF1', 'CTLA4'],
    riskFactors: [
      'Family history',
      'Female sex (2-3x higher risk)',
      'Age 40-60',
      'Smoking (strongest environmental risk)',
      'Obesity',
      'Silica exposure',
    ],
    prevention: [
      'Quit smoking',
      'Maintain healthy weight',
      'Protect joints',
      'Anti-inflammatory diet',
      'Early treatment of symptoms',
      'Regular dental care',
    ],
    prevalence: 'Affects 1.3 million Americans',
  },
  crohns_disease: {
    id: 'crohns_disease',
    name: "Crohn's Disease",
    pgsId: 'PGS000025',
    category: 'autoimmune',
    heritability: '50%',
    heritabilitySource: 'Halfvarson et al., 2003; Jostins et al., 2012',
    description: "Crohn's disease is a type of inflammatory bowel disease (IBD) that can affect any part of the gastrointestinal tract, causing abdominal pain, severe diarrhea, fatigue, and malnutrition.",
    keyGenes: ['NOD2', 'ATG16L1', 'IL23R', 'IRGM', 'LRRK2', 'CARD9'],
    riskFactors: [
      'Family history',
      'Smoking (major risk factor)',
      'Age under 30',
      'NSAIDs and antibiotics',
      'Diet high in fat and refined foods',
      'Northern climate',
    ],
    prevention: [
      'Quit smoking (most important)',
      'Anti-inflammatory diet',
      'Probiotics research ongoing',
      'Stress management',
      'Avoid unnecessary NSAIDs and antibiotics',
      'Early treatment',
    ],
    prevalence: 'Affects about 780,000 Americans',
  },
  ulcerative_colitis: {
    id: 'ulcerative_colitis',
    name: 'Ulcerative Colitis',
    pgsId: 'PGS000026',
    category: 'autoimmune',
    heritability: '30-50%',
    heritabilitySource: 'Halfvarson et al., 2003; Anderson et al., 2011',
    description: 'Ulcerative colitis is an inflammatory bowel disease causing inflammation and ulcers in the digestive tract, specifically affecting the innermost lining of the colon and rectum.',
    keyGenes: ['IL23R', 'HLA-DRB1', 'IL10', 'TNFRSF14', 'FCGR2A'],
    riskFactors: [
      'Family history',
      'Age 15-30 or 60+',
      'Jewish ancestry',
      'Previous infections',
      'Diet and gut microbiome',
    ],
    prevention: [
      'Anti-inflammatory diet',
      'Manage stress',
      'Regular exercise',
      'Adequate sleep',
      'Probiotics may help',
      'Early treatment',
    ],
    prevalence: 'Affects about 900,000 Americans',
  },
  multiple_sclerosis: {
    id: 'multiple_sclerosis',
    name: 'Multiple Sclerosis',
    pgsId: 'PGS000028',
    category: 'autoimmune',
    heritability: '25-30%',
    heritabilitySource: 'Sadovnick et al., 1996; Patsopoulos et al., 2019',
    description: 'Multiple sclerosis (MS) is a disease where the immune system attacks the protective covering of nerves, causing communication problems between the brain and body.',
    keyGenes: ['HLA-DRB1*15:01', 'IL2RA', 'IL7R', 'CD58', 'EVI5', 'CLEC16A'],
    riskFactors: [
      'Age 20-40',
      'Female sex (2-3x higher risk)',
      'Family history',
      'Low vitamin D',
      'Certain infections (EBV)',
      'Smoking',
      'Obesity',
      'Northern latitude',
    ],
    prevention: [
      'Maintain adequate vitamin D',
      'Quit smoking',
      'Maintain healthy weight',
      'Regular exercise',
      'EBV research ongoing',
    ],
    prevalence: 'Affects nearly 1 million Americans',
  },
  lupus: {
    id: 'lupus',
    name: 'Systemic Lupus Erythematosus',
    pgsId: 'PGS000030',
    category: 'autoimmune',
    heritability: '44-66%',
    heritabilitySource: 'Alarcon-Segovia et al., 2005; Bentham et al., 2015',
    description: 'Lupus is a chronic autoimmune disease where the immune system attacks healthy tissue, potentially affecting skin, joints, kidneys, brain, and other organs.',
    keyGenes: ['HLA-DR2/DR3', 'IRF5', 'STAT4', 'BLK', 'ITGAM', 'TNFAIP3'],
    riskFactors: [
      'Female sex (9x higher risk)',
      'Age 15-45',
      'African, Hispanic, Asian ancestry',
      'Family history',
      'UV light exposure',
      'Certain medications',
      'Infections',
    ],
    prevention: [
      'Sun protection',
      'Avoid smoking',
      'Healthy diet',
      'Regular exercise',
      'Stress management',
      'Avoid known triggers',
      'Early treatment',
    ],
    prevalence: 'Affects 1.5 million Americans',
  },
  celiac_disease: {
    id: 'celiac_disease',
    name: 'Celiac Disease',
    pgsId: 'PGS000035',
    category: 'autoimmune',
    heritability: '75-87%',
    heritabilitySource: 'Nistico et al., 2006; Trynka et al., 2011',
    description: 'Celiac disease is an immune reaction to eating gluten, a protein found in wheat, barley, and rye, causing damage to the small intestine lining.',
    keyGenes: ['HLA-DQ2', 'HLA-DQ8', 'IL2', 'IL21', 'SH2B3', 'CCR3'],
    riskFactors: [
      'Family history (10x higher risk)',
      'HLA-DQ2 or DQ8 genes',
      'Type 1 diabetes',
      'Down or Turner syndrome',
      'Other autoimmune diseases',
    ],
    prevention: [
      'Strict gluten-free diet (only treatment)',
      'Regular monitoring',
      'Nutritional supplementation',
      'Support groups',
      'Label reading',
    ],
    prevalence: 'Affects about 1% of population',
  },
  psoriasis: {
    id: 'psoriasis',
    name: 'Psoriasis',
    pgsId: 'PGS000036',
    category: 'autoimmune',
    heritability: '60-80%',
    heritabilitySource: 'Elder et al., 2001; Tsoi et al., 2012',
    description: 'Psoriasis is an immune-mediated disease causing raised, red, scaly patches on the skin. It is a chronic condition with periods of flare and remission.',
    keyGenes: ['HLA-C*06:02', 'IL12B', 'IL23R', 'TNFAIP3', 'TRAF3IP2', 'LCE3B/C'],
    riskFactors: [
      'Family history',
      'Stress',
      'Obesity',
      'Smoking',
      'Heavy alcohol use',
      'Infections (strep throat)',
      'Skin injury',
      'Certain medications',
    ],
    prevention: [
      'Maintain healthy weight',
      'Quit smoking',
      'Limit alcohol',
      'Stress management',
      'Moisturize skin',
      'Avoid skin trauma',
      'Early treatment',
    ],
    prevalence: 'Affects about 7.5 million Americans',
  },

  // =====================
  // RESPIRATORY (2)
  // =====================
  asthma: {
    id: 'asthma',
    name: 'Asthma',
    pgsId: 'PGS000019',
    category: 'respiratory',
    heritability: '35-70%',
    heritabilitySource: 'Duffy et al., 1990; Demenais et al., 2018',
    description: 'Asthma is a condition in which airways narrow, swell, and produce extra mucus, making breathing difficult and triggering coughing, wheezing, and shortness of breath.',
    keyGenes: ['IL33', 'IL1RL1', 'TSLP', 'IL13', 'HLA-DQ', 'ORMDL3'],
    riskFactors: [
      'Family history',
      'Allergies',
      'Respiratory infections in childhood',
      'Exposure to allergens',
      'Air pollution',
      'Obesity',
      'Smoking/secondhand smoke',
      'Occupational exposure',
    ],
    prevention: [
      'Avoid known triggers',
      'Maintain healthy weight',
      'Control allergies',
      'Avoid tobacco smoke',
      'Regular exercise',
      'Flu vaccination',
      'Good air quality',
      'Take medications as prescribed',
    ],
    prevalence: 'Affects 25 million Americans',
  },
  copd: {
    id: 'copd',
    name: 'COPD',
    pgsId: 'PGS000116',
    category: 'respiratory',
    heritability: '40-60%',
    heritabilitySource: 'Ingebrigtsen et al., 2010; Wain et al., 2017',
    description: 'Chronic obstructive pulmonary disease (COPD) is a chronic inflammatory lung disease causing obstructed airflow from the lungs. It includes emphysema and chronic bronchitis.',
    keyGenes: ['SERPINA1 (alpha-1 antitrypsin)', 'HHIP', 'FAM13A', 'CHRNA3/5', 'IREB2'],
    riskFactors: [
      'Smoking (80-90% of cases)',
      'Secondhand smoke',
      'Occupational dust and chemicals',
      'Indoor air pollution',
      'Alpha-1 antitrypsin deficiency',
      'Age',
      'Asthma history',
    ],
    prevention: [
      'Never smoke or quit smoking',
      'Avoid secondhand smoke',
      'Reduce occupational exposures',
      'Flu and pneumonia vaccinations',
      'Regular exercise',
      'Pulmonary rehabilitation',
    ],
    prevalence: 'Affects 16 million Americans',
  },

  // =====================
  // OPHTHALMOLOGIC (2)
  // =====================
  glaucoma: {
    id: 'glaucoma',
    name: 'Glaucoma',
    pgsId: 'PGS000042',
    category: 'ophthalmologic',
    heritability: '50-65%',
    heritabilitySource: 'Wang et al., 2010; Gharahkhani et al., 2021',
    description: 'Glaucoma is a group of eye conditions that damage the optic nerve, often due to abnormally high pressure in the eye. It is a leading cause of blindness for people over 60.',
    keyGenes: ['MYOC', 'OPTN', 'WDR36', 'CAV1/CAV2', 'SIX6', 'TMCO1', 'CDKN2B-AS1'],
    riskFactors: [
      'High intraocular pressure',
      'Age over 60',
      'African or Hispanic ancestry',
      'Family history',
      'Extreme nearsightedness',
      'Thin corneas',
      'Diabetes',
      'Eye injury history',
    ],
    prevention: [
      'Regular comprehensive eye exams',
      'Know family eye health history',
      'Exercise regularly',
      'Use prescribed eye drops',
      'Protect eyes from injury',
      'Early detection is key',
    ],
    prevalence: 'Affects 3 million Americans',
  },
  macular_degeneration: {
    id: 'macular_degeneration',
    name: 'Age-Related Macular Degeneration',
    pgsId: 'PGS000056',
    category: 'ophthalmologic',
    heritability: '45-70%',
    heritabilitySource: 'Seddon et al., 2005; Fritsche et al., 2016',
    description: 'AMD is an eye disease that blurs the central vision needed for activities like reading and driving. It is caused by damage to the macula, the part of the eye that controls sharp, central vision.',
    keyGenes: ['CFH', 'ARMS2/HTRA1', 'C3', 'CFB', 'VEGFA', 'APOE'],
    riskFactors: [
      'Age over 50',
      'Smoking (2x risk)',
      'Family history',
      'Caucasian race',
      'Cardiovascular disease',
      'Obesity',
      'Light-colored eyes',
    ],
    prevention: [
      'Quit smoking',
      'Regular eye exams',
      'Heart-healthy diet (leafy greens, fish)',
      'AREDS supplements if indicated',
      'Protect eyes from UV light',
      'Maintain healthy blood pressure and cholesterol',
      'Regular exercise',
    ],
    prevalence: 'Affects 11 million Americans',
  },

  // =====================
  // MUSCULOSKELETAL (2)
  // =====================
  osteoporosis: {
    id: 'osteoporosis',
    name: 'Osteoporosis',
    pgsId: 'PGS000045',
    category: 'musculoskeletal',
    heritability: '50-80%',
    heritabilitySource: 'Ralston & Uitterlinden, 2010; Zheng et al., 2012',
    description: 'Osteoporosis causes bones to become weak and brittle, so brittle that a fall or even mild stresses like bending over can cause a fracture.',
    keyGenes: ['RANKL', 'OPG', 'LRP5', 'ESR1', 'SOST', 'WNT16'],
    riskFactors: [
      'Female sex',
      'Older age',
      'Small body frame',
      'Family history',
      'Low calcium/vitamin D',
      'Sedentary lifestyle',
      'Excessive alcohol',
      'Smoking',
      'Certain medications (steroids)',
    ],
    prevention: [
      'Adequate calcium and vitamin D',
      'Weight-bearing exercise',
      'Strength training',
      'Avoid smoking',
      'Limit alcohol',
      'Bone density testing',
      'Fall prevention',
      'Medications when indicated',
    ],
    prevalence: 'Affects 10 million Americans',
  },
  osteoarthritis: {
    id: 'osteoarthritis',
    name: 'Osteoarthritis',
    pgsId: 'PGS000107',
    category: 'musculoskeletal',
    heritability: '40-65%',
    heritabilitySource: 'Spector & MacGregor, 2004; Zengini et al., 2018',
    description: 'Osteoarthritis is the most common form of arthritis, occurring when protective cartilage that cushions the ends of bones wears down over time.',
    keyGenes: ['GDF5', 'SMAD3', 'COL11A1', 'RUNX2', 'ALDH1A2'],
    riskFactors: [
      'Older age',
      'Obesity',
      'Joint injuries',
      'Repetitive joint stress',
      'Female sex',
      'Genetics',
      'Bone deformities',
      'Certain metabolic diseases',
    ],
    prevention: [
      'Maintain healthy weight',
      'Stay physically active',
      'Avoid repetitive joint stress',
      'Strengthen muscles around joints',
      'Protect joints from injury',
      'Good posture',
    ],
    prevalence: 'Affects over 32 million US adults',
  },

  // =====================
  // DERMATOLOGIC (2)
  // =====================
  eczema: {
    id: 'eczema',
    name: 'Atopic Dermatitis / Eczema',
    pgsId: 'PGS000037',
    category: 'dermatologic',
    heritability: '70-80%',
    heritabilitySource: 'Weidinger et al., 2006; Paternoster et al., 2015',
    description: 'Atopic dermatitis (eczema) is a condition that makes skin red and itchy. It is common in children but can occur at any age and is often associated with allergies and asthma.',
    keyGenes: ['FLG (filaggrin)', 'IL4', 'IL13', 'OVOL1', 'ACTL9', 'KIF3A'],
    riskFactors: [
      'Family history of eczema, allergies, or asthma',
      'Living in urban areas',
      'Cold, dry climates',
      'Food allergies',
      'Environmental allergens',
      'Stress',
    ],
    prevention: [
      'Keep skin moisturized',
      'Avoid known triggers',
      'Use gentle, fragrance-free products',
      'Avoid extreme temperatures',
      'Manage stress',
      'Wear soft fabrics',
      'Keep nails short',
    ],
    prevalence: 'Affects 31 million Americans',
  },
  vitiligo: {
    id: 'vitiligo',
    name: 'Vitiligo',
    pgsId: 'PGS000034',
    category: 'dermatologic',
    heritability: '50-80%',
    heritabilitySource: 'Jin et al., 2012; Spritz & Andersen, 2017',
    description: 'Vitiligo is a condition causing loss of skin color in patches. It occurs when pigment-producing cells die or stop functioning.',
    keyGenes: ['TYR', 'OCA2', 'HLA-A', 'PTPN22', 'NLRP1', 'XBP1'],
    riskFactors: [
      'Family history',
      'Autoimmune diseases',
      'Sunburn or skin trauma',
      'Stress',
      'Chemical exposure',
    ],
    prevention: [
      'Sun protection',
      'Avoid skin trauma',
      'Manage stress',
      'Early treatment may limit spread',
      'Support groups',
    ],
    prevalence: 'Affects 1-2% of world population',
  },

  // =====================
  // RENAL (2)
  // =====================
  chronic_kidney_disease: {
    id: 'chronic_kidney_disease',
    name: 'Chronic Kidney Disease',
    pgsId: 'PGS000110',
    category: 'renal',
    heritability: '30-50%',
    heritabilitySource: 'Pattaro et al., 2016; Wuttke et al., 2019',
    description: 'Chronic kidney disease (CKD) involves gradual loss of kidney function over time. The kidneys filter wastes and excess fluids from blood.',
    keyGenes: ['UMOD', 'SHROOM3', 'SLC7A9', 'APOL1 (in African ancestry)', 'PKD1/2'],
    riskFactors: [
      'Diabetes',
      'High blood pressure',
      'Heart disease',
      'Family history',
      'Obesity',
      'Older age',
      'African ancestry (APOL1)',
      'Smoking',
    ],
    prevention: [
      'Control blood pressure',
      'Manage diabetes',
      'Healthy diet (low sodium)',
      'Maintain healthy weight',
      'Quit smoking',
      'Limit NSAIDs',
      'Stay hydrated',
      'Regular kidney function tests',
    ],
    prevalence: 'Affects 37 million US adults',
  },
  kidney_stones: {
    id: 'kidney_stones',
    name: 'Kidney Stones',
    pgsId: 'PGS000112',
    category: 'renal',
    heritability: '45-57%',
    heritabilitySource: 'Goldfarb et al., 2005; Thorleifsson et al., 2009',
    description: 'Kidney stones are hard deposits made of minerals and salts that form inside the kidneys and can affect any part of the urinary tract.',
    keyGenes: ['SLC26A6', 'CLDN14', 'ALPL', 'CASR', 'DGKH'],
    riskFactors: [
      'Dehydration',
      'High-sodium diet',
      'Obesity',
      'Family history',
      'High-protein diet',
      'Certain medications',
      'Inflammatory bowel disease',
      'Recurrent UTIs',
    ],
    prevention: [
      'Drink plenty of water (2-3 liters/day)',
      'Reduce sodium intake',
      'Eat moderate protein',
      'Avoid excessive oxalate foods',
      'Get adequate calcium from food',
      'Maintain healthy weight',
    ],
    prevalence: '1 in 11 people will have a kidney stone',
  },

  // =====================
  // ENDOCRINE (2)
  // =====================
  hypothyroidism: {
    id: 'hypothyroidism',
    name: 'Hypothyroidism',
    pgsId: 'PGS000095',
    category: 'endocrine',
    heritability: '65%',
    heritabilitySource: 'Hansen et al., 2006; Teumer et al., 2018',
    description: 'Hypothyroidism is a condition where the thyroid gland does not produce enough thyroid hormone, leading to fatigue, weight gain, and other symptoms.',
    keyGenes: ['FOXE1', 'CAPZB', 'PDE8B', 'NKX2-1', 'VAV3'],
    riskFactors: [
      'Female sex (8x more common)',
      'Age over 60',
      'Family history',
      'Autoimmune diseases',
      'Previous thyroid surgery or radiation',
      'Pregnancy',
      'Iodine deficiency or excess',
    ],
    prevention: [
      'Adequate iodine intake',
      'Regular thyroid screening',
      'Manage autoimmune conditions',
      'Avoid excessive iodine supplements',
      'Regular medical checkups',
    ],
    prevalence: 'Affects about 5% of US adults',
  },
  hyperthyroidism: {
    id: 'hyperthyroidism',
    name: 'Hyperthyroidism',
    pgsId: 'PGS000096',
    category: 'endocrine',
    heritability: '60-80%',
    heritabilitySource: 'Brix et al., 2001; Teumer et al., 2018',
    description: 'Hyperthyroidism occurs when the thyroid gland produces too much thyroid hormone, causing rapid heartbeat, weight loss, nervousness, and other symptoms.',
    keyGenes: ['TSHR', 'HLA-DRB1', 'CTLA4', 'PTPN22', 'FCRL3'],
    riskFactors: [
      'Female sex',
      'Family history of thyroid disease',
      'Graves\' disease',
      'Excess iodine intake',
      'Type 1 diabetes or other autoimmune diseases',
      'Recent pregnancy',
    ],
    prevention: [
      'Avoid excessive iodine',
      'Regular thyroid monitoring',
      'Manage autoimmune conditions',
      'Don\'t smoke',
      'Stress management',
    ],
    prevalence: 'Affects about 1.2% of US adults',
  },
};

// Utility function to get diseases by category
export function getDiseasesByCategory() {
  const byCategory = {};

  Object.entries(DISEASE_CATEGORIES).forEach(([key, category]) => {
    byCategory[key] = {
      ...category,
      diseases: Object.values(DISEASES).filter(d => d.category === key),
    };
  });

  return byCategory;
}

// Utility function to get disease by ID
export function getDiseaseById(id) {
  return DISEASES[id] || null;
}

// Utility function to get all diseases as array
export function getAllDiseases() {
  return Object.values(DISEASES);
}

// Utility function to search diseases
export function searchDiseases(query) {
  const lowerQuery = query.toLowerCase();
  return Object.values(DISEASES).filter(disease =>
    disease.name.toLowerCase().includes(lowerQuery) ||
    disease.description.toLowerCase().includes(lowerQuery) ||
    disease.keyGenes.some(gene => gene.toLowerCase().includes(lowerQuery))
  );
}

export default DISEASES;
